import json
import re
import sys

d = json.load(sys.stdin)
f = d.get("tool_input", {}).get("file_path", "")

if re.search(r"/doctype/[^/]+/[^/]+\.json$", f):
	print(
		json.dumps(
			{
				"hookSpecificOutput": {
					"hookEventName": "PreToolUse",
					"permissionDecision": "deny",
					"permissionDecisionReason": (
						"DocType JSON files are normally generated by Frappe, not hand-edited. "
						"Ask the user to make this change via the Frappe Desk UI in developer mode "
						"(bench set-config developer_mode 1, then edit/create the DocType in the "
						"browser) - saving there auto-exports the JSON. File: " + f
					),
				}
			}
		)
	)
elif re.search(r"/fixtures/custom_field\.json$", f):
	print(
		json.dumps(
			{
				"hookSpecificOutput": {
					"hookEventName": "PreToolUse",
					"permissionDecision": "deny",
					"permissionDecisionReason": (
						"Custom Field fixtures are normally generated by Frappe, not hand-edited. "
						"Ask the user to add the custom field via the Frappe Desk UI in developer "
						"mode, then export fixtures (bench export-fixtures). File: " + f
					),
				}
			}
		)
	)
